# Generated by Django 2.1.3 on 2018-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181124_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(max_length=450),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(max_length=450),
        ),
    ]
