# Generated by Django 2.1.3 on 2018-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181124_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(),
        ),
    ]
